version: "3.9"
services:
  edu-cl-api:
    image: tojatos/edu-cl-api
    restart: always
    build: src
    networks:
      - web
      - default
    environment:
      - ROOT_PATH=/edu-cl-api
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.edu-cl-api-stripprefix.stripPrefix.prefixes=/edu-cl-api"
      - "traefik.http.routers.edu-cl-api.rule=((Host(`krzysztofruczkowski.pl`) || Host(`www.krzysztofruczkowski.pl`)) && PathPrefix(`/edu-cl-api/`))"
      - "traefik.http.routers.edu-cl-api.middlewares=edu-cl-api-stripprefix"
      - "traefik.http.routers.edu-cl-api.entrypoints=websecure"
      - "traefik.http.routers.edu-cl-api.tls=true"
      - "traefik.http.routers.edu-cl-api.tls.certresolver=myresolver"
      - "traefik.http.services.edu-cl-api.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_default"

networks:
  web:
    name: traefik_default
    external: true
