version: "3.9"
services:
  edu-cl-api:
    image: tojatos/edu-cl-api
    restart: always
    build: src
    ports:
      - "80:80"
    environment:
      - GUNICORN_CMD_ARGS='--root-path /edu-cl-api/api'
